// Generated by gencpp from file space_invaders_ros/GetUserScore.msg
// DO NOT EDIT!


#ifndef SPACE_INVADERS_ROS_MESSAGE_GETUSERSCORE_H
#define SPACE_INVADERS_ROS_MESSAGE_GETUSERSCORE_H

#include <ros/service_traits.h>


#include <space_invaders_ros/GetUserScoreRequest.h>
#include <space_invaders_ros/GetUserScoreResponse.h>


namespace space_invaders_ros
{

struct GetUserScore
{

typedef GetUserScoreRequest Request;
typedef GetUserScoreResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetUserScore
} // namespace space_invaders_ros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::space_invaders_ros::GetUserScore > {
  static const char* value()
  {
    return "ce20595763f2770f6e27a12a2546995d";
  }

  static const char* value(const ::space_invaders_ros::GetUserScore&) { return value(); }
};

template<>
struct DataType< ::space_invaders_ros::GetUserScore > {
  static const char* value()
  {
    return "space_invaders_ros/GetUserScore";
  }

  static const char* value(const ::space_invaders_ros::GetUserScore&) { return value(); }
};


// service_traits::MD5Sum< ::space_invaders_ros::GetUserScoreRequest> should match
// service_traits::MD5Sum< ::space_invaders_ros::GetUserScore >
template<>
struct MD5Sum< ::space_invaders_ros::GetUserScoreRequest>
{
  static const char* value()
  {
    return MD5Sum< ::space_invaders_ros::GetUserScore >::value();
  }
  static const char* value(const ::space_invaders_ros::GetUserScoreRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::space_invaders_ros::GetUserScoreRequest> should match
// service_traits::DataType< ::space_invaders_ros::GetUserScore >
template<>
struct DataType< ::space_invaders_ros::GetUserScoreRequest>
{
  static const char* value()
  {
    return DataType< ::space_invaders_ros::GetUserScore >::value();
  }
  static const char* value(const ::space_invaders_ros::GetUserScoreRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::space_invaders_ros::GetUserScoreResponse> should match
// service_traits::MD5Sum< ::space_invaders_ros::GetUserScore >
template<>
struct MD5Sum< ::space_invaders_ros::GetUserScoreResponse>
{
  static const char* value()
  {
    return MD5Sum< ::space_invaders_ros::GetUserScore >::value();
  }
  static const char* value(const ::space_invaders_ros::GetUserScoreResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::space_invaders_ros::GetUserScoreResponse> should match
// service_traits::DataType< ::space_invaders_ros::GetUserScore >
template<>
struct DataType< ::space_invaders_ros::GetUserScoreResponse>
{
  static const char* value()
  {
    return DataType< ::space_invaders_ros::GetUserScore >::value();
  }
  static const char* value(const ::space_invaders_ros::GetUserScoreResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SPACE_INVADERS_ROS_MESSAGE_GETUSERSCORE_H
