// Generated by gencpp from file space_invaders_ros/SetGameDifficulty.msg
// DO NOT EDIT!


#ifndef SPACE_INVADERS_ROS_MESSAGE_SETGAMEDIFFICULTY_H
#define SPACE_INVADERS_ROS_MESSAGE_SETGAMEDIFFICULTY_H

#include <ros/service_traits.h>


#include <space_invaders_ros/SetGameDifficultyRequest.h>
#include <space_invaders_ros/SetGameDifficultyResponse.h>


namespace space_invaders_ros
{

struct SetGameDifficulty
{

typedef SetGameDifficultyRequest Request;
typedef SetGameDifficultyResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetGameDifficulty
} // namespace space_invaders_ros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::space_invaders_ros::SetGameDifficulty > {
  static const char* value()
  {
    return "9d6c7c12eefb5ab4ae8ce42c4c512e6f";
  }

  static const char* value(const ::space_invaders_ros::SetGameDifficulty&) { return value(); }
};

template<>
struct DataType< ::space_invaders_ros::SetGameDifficulty > {
  static const char* value()
  {
    return "space_invaders_ros/SetGameDifficulty";
  }

  static const char* value(const ::space_invaders_ros::SetGameDifficulty&) { return value(); }
};


// service_traits::MD5Sum< ::space_invaders_ros::SetGameDifficultyRequest> should match
// service_traits::MD5Sum< ::space_invaders_ros::SetGameDifficulty >
template<>
struct MD5Sum< ::space_invaders_ros::SetGameDifficultyRequest>
{
  static const char* value()
  {
    return MD5Sum< ::space_invaders_ros::SetGameDifficulty >::value();
  }
  static const char* value(const ::space_invaders_ros::SetGameDifficultyRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::space_invaders_ros::SetGameDifficultyRequest> should match
// service_traits::DataType< ::space_invaders_ros::SetGameDifficulty >
template<>
struct DataType< ::space_invaders_ros::SetGameDifficultyRequest>
{
  static const char* value()
  {
    return DataType< ::space_invaders_ros::SetGameDifficulty >::value();
  }
  static const char* value(const ::space_invaders_ros::SetGameDifficultyRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::space_invaders_ros::SetGameDifficultyResponse> should match
// service_traits::MD5Sum< ::space_invaders_ros::SetGameDifficulty >
template<>
struct MD5Sum< ::space_invaders_ros::SetGameDifficultyResponse>
{
  static const char* value()
  {
    return MD5Sum< ::space_invaders_ros::SetGameDifficulty >::value();
  }
  static const char* value(const ::space_invaders_ros::SetGameDifficultyResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::space_invaders_ros::SetGameDifficultyResponse> should match
// service_traits::DataType< ::space_invaders_ros::SetGameDifficulty >
template<>
struct DataType< ::space_invaders_ros::SetGameDifficultyResponse>
{
  static const char* value()
  {
    return DataType< ::space_invaders_ros::SetGameDifficulty >::value();
  }
  static const char* value(const ::space_invaders_ros::SetGameDifficultyResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SPACE_INVADERS_ROS_MESSAGE_SETGAMEDIFFICULTY_H
